In [6]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

# Example Corpus
corpus = ["cat", "dog", "fish", "cat", "dog", "cat"]
corpus

['cat', 'dog', 'fish', 'cat', 'dog', 'cat']

In [9]:
# Convert to NumPy array and reshape
corpus_array = np.array(corpus).reshape(-1, 1)
corpus_array

array([['cat'],
       ['dog'],
       ['fish'],
       ['cat'],
       ['dog'],
       ['cat']], dtype='<U4')

In [ ]:
# Apply One-Hot Encoding
encoder = OneHotEncoder(sparse_output=False)
one_hot_encoded = encoder.fit_transform(corpus_array)


[array(['cat', 'dog', 'fish'], dtype='<U4')]

In [ ]:
print(encoder.get_feature_names_out())
print(one_hot_encoded)

[array(['cat', 'dog', 'fish'], dtype='<U4')]
['x0_cat' 'x0_dog' 'x0_fish']
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]
